---
  name: Docker Build and Push
  
  on:
    push:
      branches:
      - main
      tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      
      - name: create branch
        run: git checkout -b ${{ steps.vars.outputs.sha_short }}
          
      - name: echo test 
        run:  echo 'hi' >> README.md

      - name: git add, configure author, commit and push
        run: |
          git add README.md
          git config user.name "GitHubActions"
          git config user.email "<>"
          git commit -m "update -version ???"
          git push --set-upstream origin ${{ steps.vars.outputs.sha_short }}
      
      - name: setup PR with new version for images 
        run: gh pr create --title 'titlevar' --body 'bodyvar' --base main
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
