---
  name: Docker Build and Push
  
  on:
    push:
      branches:
      - main
      tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      
      - name: create branch
        run: git checkout -b ${{ github.sha }}
          
      - name: echo test 
        run:  echo hi >> README.md

      - name: git add and commit
        run: |
          git add README.md
          git commit -m "update version ???"
      
      - name: setup PR with new version for images 
        run: gh pr create --title 'titlevar' --body 'bodyvar' --base main
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
