---
  name: Docker Build and Push
  
  on:
    push:
      branches:
      - main
      tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      
      - name: setup PR with new version for images 
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'argocd/stage/luxplus/be/Values.yaml' 
          propertyPath: 'phpfpm_image_version'
          value: '0.0.1'
          # branch: main/thisshouldbevar
          # targetBranch: main
          # createPR: true
          # message: 'Update Image Version to' 
